# pre-trained model path
prev_path: "urchade/gliner_base"

# Training Parameters
num_steps: 5000
train_batch_size: 8
eval_every: 500
warmup_ratio: 0.1
scheduler_type: "cosine"

# loss function
loss_alpha: -1 # focal loss alpha, if -1, no focal loss
loss_gamma: 0 # focal loss gamma, if 0, no focal loss
loss_reduction: "sum"

# Learning Rate and weight decay Configuration
lr_encoder: 1e-5
lr_others: 5e-5
weight_decay_encoder: 0.01
weight_decay_other: 0.01

# Directory Paths
root_dir: finetune_logs
train_data: "data/pilener_train.json" # see https://github.com/urchade/GLiNER/tree/main/data
val_data_dir: "data/NER_datasets"
# "NER_datasets": val data from the paper can be obtained from "https://drive.google.com/file/d/1T-5IbocGka35I7X3CE6yKe5N_Xg2lVKT/view"

# Advanced Training Settings
size_sup: -1
max_types: 25
shuffle_types: true
random_drop: true
max_neg_type_ratio: 1
max_len: 384
freeze_token_rep: false
save_total_limit: 20